### ISSUE TITLE
Last Kraken update broke the plugin somehow

### ISSUE THREAD

**Issue by NewProggie** [aaronk6/Kraken-MoneyMoney#2]
After the last downtime for two days of the Kraken exchange, your plugin doesn't seem to work anomyore. Updating the account gives the following error message:

    Kraken.lua:174: bad argument #1 to 'pairs' (table expected, got nil)

However, if I try to call the API directly it seems to work fine:

    $ curl https://api.kraken.com/0/public/AssetPairs
    {"error":[],"result":{"BCHEUR":{"altname":"BCHEUR","aclass_base":"currency","base":"BCH","aclass_quote":"currency","quote":"ZEUR","lot":"unit","pair_decimals":1,"lot_decimals":8,"lot_multiplier":1,"leverage_buy":[],"leverage_sell":[],"fees":[[0,0],[50000,0],[100000,0],[250000,0],[500000,0],[1000000,0],[2500000,0],[5000000,0],[10000000,0]],"fees_maker":[[0,-0.1], ...

**Edit:**
Here's also some output from the MM protocol window, when trying to execute an update on my Kraken account:

    1> Sending: POST https://api.kraken.com/0/public/AssetPairs
    11:49:24  1> Received: {"error":[],"result":{"BCHEUR":
    {"altname":"BCHEUR","aclass_base":"currency", ...
          1> nil
          1> Kraken.lua:179: bad argument #1 to 'pairs' (table expected, got nil)

**Comment by aaronk6** [comment]
Thanks for reporting this. I also noticed this and will have a look!

**Comment by NewProggie** [comment]
It seems that the resulting JSON from the Kraken API is broken somehow, but after checking it (using http://jsoneditoronline.org/) it seems to be valid though

**Comment by aaronk6** [comment]
I think it’s a bug in MoneyMoney’s JSON parser. Maybe there’s a size limit. Here’s what I’ve found out:

* It works with a different JSON parser (this one: https://gist.githubusercontent.com/tylerneylon/59f4bcf316be525b30ab/raw/7f69cc2cea38bf68298ed3dbfc39d197d53c80de/json.lua)
* It works when I manually remove two asset pairs from the Kraken JSON response before feeding it into MoneyMoney’s JSON parser

I’ll get in touch with the author of MoneyMoney to see if he can fix this.

**Comment by cryptochrome** [comment]
Don't forget that Kraken was completely down for three days and they are just starting back up now with a couple of features disabled. Keep that in mind :)

**Comment by aaronk6** [comment]
@cryptochrome Thanks for mentioning this, but the response from Kraken looks fine and is valid JSON. I’m almost sure that there’s something wrong with MoneyMoney’s JSON parser.

**Comment by NewProggie** [comment]
&aaronk6: Yes, that’s what I found out myself as well. Maybe it broke with the last MM update. Thanks for taking care of this.

**Comment by aaronk6** [comment]
Michael Haller, the creator of MoneyMoney, has just fixed the issue and has sent me a private beta build. As expected, there was a size limitation in the JSON parser which has now been removed. I just checked and this indeed fixes the issue 🎉

So you guys will just need to wait for the next MoneyMoney update and the issue will be gone.

**Comment by NewProggie** [comment]
Nice, well done. Thanks

**Comment by aaronk6** [comment]
I have asked Michael when the next MoneyMoney version will be released. He said it won’t be later than March 2018. Since this is quite a long time, he was so kind to sent me a fix for my extension to make it work with the current version of MoneyMoney (2.3.3). I’ve just committed it and are now awaiting the signed extension from him.

**Comment by aaronk6** [comment]
… and it’s signed.

https://github.com/aaronk6/Kraken-MoneyMoney/releases/tag/v1.03

**Comment by NewProggie** [comment]
Well, unfortunately for the following error still remains:

    Kraken.lua:190: bad argument #1 to 'pairs' (table expected, got nil)

Any idea, what's going on here?

**Comment by aaronk6** [comment]
Are you on MoneyMoney 2.3.4 (306) Beta? The workaround is only 2.3.3 and older, so it’s likely that this is the cause. So you will either need to wait for the next MoneyMoney beta build, or manually edit the script (line 166) to apply the workaround for anything lower than 2.3.5 (plus, disable extension signing in the preferences). Sorry for the trouble!

**Comment by NewProggie** [comment]
Yip, that solved the issue. Thanks for reaching out again and answering. I can finally enjoy my Kraken account via MM again. You're officially awesome!

**Comment by aaronk6** [comment]
Yeah! Happy to hear!

**Comment by cubistico** [comment]
Followed this discussion today, thanks for the quick reaction!
However, I updated MM to 2.3.4 (306) Beta and replaced the kraken.lua by 1.03, but I still get `Kraken.lua:190: bad argument #1 to 'pairs' (table expected, got nil)`. 
Did I miss something?

**Comment by NewProggie** [comment]
@cubistico Did you change it to 2.3.5? Can we see your fix here, please?

**Comment by cubistico** [comment]
Do I need to fix something by myself? Then that's probably what I'm missing. I thought the fix is in kraken.lua 1.03 in combination with  MM to 2.3.4 (306) Beta. What is it that I have to change to 2.3.5?

**Comment by NewProggie** [comment]
Swap Kraken.lua line 166 with:

    local fixVersion = '2.3.5'

and as described above don't forget to disable signature checking.

**Comment by aaronk6** [comment]
@cubistico My fix is only for MoneyMoney 2.3.3 (the current stable version), as 2.3.4 won’t need the workaround once it’s released. So if you don’t want to wait, you’ll either need to edit the script manually (see @NewProggie’s answer above), or go back to MoneyMoney 2.3.3 (probably cumbersome because it won’t accept a newer database).

**Comment by cubistico** [comment]
Thanks, guys. Now I understand. I applied the fix and it works perfectly. Two thumbs up!

**Comment by aaronk6** [comment]
Looks like it broke again. @NewProggie or @cubistico, can you confirm? See issue #3.

**Comment by cubistico** [comment]
Yes, confirmed. Seems to have changed today around/after noon CET.

**Comment by NewProggie** [comment]
Yup, unfortunately broken again :-( Any idea why?

**Comment by aaronk6** [comment]
Yes, see my comment in #3. There will be another fix later today.

**Comment by aaronk6** [comment]
@NewProggie Just posted the fix and some background info to #3.
